version: '3.8'

services:
  backend:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=artsite;Username=postgres;Password=postgres
    volumes:
      - art_uploads:/app/Uploads
    depends_on:
      - db

  frontend:
    build: ArtSite.Frontend/Neospiration
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=artsite
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  art_uploads: